---
# The Full role need to be executed in "become"
ansible_become: yes

# List of variables required for the run of that playbooks
required_vars:
  - fail2ban_destmail

# fail2ban.local
fail2ban_loglevel: "{{ 'INFO' if (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('16.04', '>=') or ansible_distribution == 'Debian' and ansible_distribution_version is version('9', '>=')) else 3 }}"
fail2ban_dbpurgeage: 2d

# jail.local
fail2ban_ignoreip:
  - 127.0.0.1/8

fail2ban_bantime: 10m
fail2ban_findtime: 10m
fail2ban_maxretry: 5
fail2ban_backend: auto
fail2ban_usedns: warn
fail2ban_banaction: iptables-multiport
fail2ban_banaction_allports: iptables-allports
fail2ban_action: '%(action_)s'

fail2ban_jails:
  - name: sshd
    enabled: true
    port: ssh
    filter: sshd
    logpath: '%(sshd_log)s'
    backend: '%(sshd_backend)s'
  - name: recidive
    enabled: true
    filter: recidive
    logpath: /var/log/fail2ban.log
    bantime: 2d
    findtime: 2d 
    maxretry: 3 