---
- name: Firewall - Ensure iptables is present.
  package:
    name: iptables
    state: present

- name: Firewall - Load Docker Service Fact
  service_facts:

- name: Firewall - Creates directory
  file:
    path: /etc/firewall
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Firewall - Add Iptables rules file
  template:
    src: firewall.sh.j2
    dest: /etc/firewall/firewall.sh
    owner: root
    group: root
    mode: 0744

- name: Firewall - Add init.d startup script
  template:
    src: firewall.init.j2
    dest: /etc/init.d/firewall
    owner: root
    group: root
    mode: 0744
  when: "ansible_service_mgr != 'systemd'"

- name: Firewall - Add systemd startup script
  template:
    src: firewall.unit.j2
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: 0644
  when: "ansible_service_mgr == 'systemd'"

- name: Firewall - Launch iptables manually first
  shell: /etc/firewall/firewall.sh &
  run_once: yes

- name: Firewall - Manage firewall service
  service:
    name: firewall
    state: "{{ firewall_state }}"
    enabled: "{{ firewall_enabled_at_boot }}"

- name: Firewall - Disable other firewalls system
  import_tasks: disable-other-firewalls.yml
  when: firewall_disable_firewalld or firewall_disable_ufw