---
- name: Apply Firewall on VPN
  hosts: all
  become: yes
  pre_tasks:
  - name: Set Iptables rules for VPN
    set_fact:
      # Default Policies
      firewall_default_input: DROP
      firewall_default_output: DROP
      firewall_default_forward: DROP
      firewall_allowed_input_tcp_ports:
      - 443
      # Authorize SSH from bastion and awx
      firewall_additional_rules:
      - "iptables -t filter -A INPUT -p tcp -s {{ network.private_range | ipaddr('address') | ipmath(1) }} --dport 22 -j ACCEPT"
      - "iptables -t filter -A INPUT -p tcp -s {{ network.private_range | ipaddr('address') | ipmath(2) }} --dport 22 -j ACCEPT"

  - name: Set Iptables rules if openVpn is in traversal mode
    set_fact:
      # Authorize internet access to bastion and awx
      firewall_masquerade_enabled: true
      firewall_masquerade_authorized_ips:
      - "10.8.0.0/24"
      firewall_additional_rules: "{{ firewall_additional_rules + vpn_nat_additional_rules }}"
    vars:
      vpn_nat_additional_rules:
        - "iptables -t filter -A FORWARD -i tun+ -j ACCEPT"
        - "iptables -t filter -A FORWARD -o tun+ -j ACCEPT"
    when: extras.vpn.route_traffic == True

  roles:
    - mderasse.firewall