- name: Rkhunter - Add Epel repository
  yum:
    name: epel-release
    update_cache: true
    state: latest

- name: Rkhunter - Install rkhunter package
  yum:
    name: rkhunter
    state: latest
  notify:
    - launch propupd