---
- name: Apply Basic Roles on Gateway
  hosts: all
  become: yes
  pre_tasks:
    - name: Load Default Debian Config
      include_tasks: ../../config/debian.yml

    - name: Launch Default Debian Pre Tasks
      include_tasks: ../../base/pretask_debian.yml

    # SSH + SSH DDOS + Nginx
    - name: Enable Jails on fail2ban
      set_fact:
        fail2ban_jails:
          - name: sshd
            enabled: true
            filter: sshd
          - name: ssh-ddos
            enabled: true
            filter: ssh-ddos
          - name: recidive
            enabled: true
            filter: recidive
            logpath: /var/log/fail2ban.log
            bantime: 2d
            findtime: 2d 
            maxretry: 3 
          - name: nginx-http-auth
            enabled: true
            filter: nginx-http-auth

    - name: Set Special Sysctl configuration for Gateway
      set_fact:
        sysctl_overwrite:
          net.ipv4.ip_forward: 1

  roles:
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
    - mderasse.fail2ban
    - mderasse.rkhunter
    - mderasse.bastion_client
    - geerlingguy.ntp

