---
- name: Install WebServer for Proxy on Gateway
  hosts: all
  become: yes
  pre_tasks:
      
    - name: WebServer - Load Configuration for Management Gateway
      include_tasks: webserver/management.yml
      when: "'management' in group_names"

    - name: WebServer - Disable Nginx template 
      set_fact:
        nginx_http_template_enable: false

    - name: WebServer - Check that www-data user exist
      shell: grep "^www-data:" /etc/passwd
      ignore_errors: yes
      register: wwwdata_exist

    - name: WebServer - Install Nginx
      include_role:
        name: nginxinc.nginx
      when: wwwdata_exist.rc != 0

    - name: WebServer - Creates SSL Nginx directory
      file:
        path: /etc/nginx/ssl
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: WebServer - Generate Diffie-Hellman for nginx
      openssl_dhparam:
        path: /etc/nginx/ssl/dhparam4.pem
        owner: root
        group: root
        mode: 0644

    - name: WebServer - Enable Nginx template 
      set_fact:
        nginx_http_template_enable: true

  roles:
    - geerlingguy.certbot
    - nginxinc.nginx